// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrekigsesnqdhexflbcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyZWtpZ3Nlc25xZGhleGZsYmNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2OTk0NjUsImV4cCI6MjA5MjI3NTQ2NX0.V_lzEcvieG8vrJCA8jeXmEJ95CKtQi5AkSa6n0HKBLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});